<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/domain/show.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="user" />: <fmt:message key="crud.functionalities.show" /></title>
</head>
<body>

	<a href="${pageContext.request.contextPath}/domain/user/search" class="ajaxy button button-search"><fmt:message key="user" /></a>
	<span class="ui-state-highlight button button-show"><fmt:message key="crud.show.button" /></span>
	<a href="${pageContext.request.contextPath}/domain/user/update/${user.primaryKey}" class="ajaxy button button-edit"><fmt:message key="crud.edit.button" /></a>
	<a href="${pageContext.request.contextPath}/domain/user/delete/${user.primaryKey}" class="modal button button-delete"><fmt:message key="crud.delete.button" /></a>

	<table class="show">
		<tbody>
			<tr>
				<th><fmt:message key="user_emailaddress" /></th>
				<td><spring:eval expression="user.emailaddress"/></td>
			</tr>
			<tr>
				<th><fmt:message key="user_password" /></th>
				<td><spring:eval expression="user.password"/></td>
			</tr>
			<tr>
				<th><fmt:message key="user_enabled" /></th>
				<td><spring:eval expression="user.enabled"/></td>
			</tr>
			<tr>
				<th><fmt:message key="role" /></th>
				<td>
					<ul class="inline">
						<c:forEach items="${user.roles}" var="role" varStatus="status">
							<li>
								<spring:eval expression="role" /><a href="${pageContext.request.contextPath}/domain/role/show/${role.primaryKey}" class="button button-show miniature"><fmt:message key="crud.show.button" /></a>
							</li>
						</c:forEach>
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
</body>