<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/domain/update.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="user" />: <fmt:message key="crud.functionalities.update" /></title>
</head>
<body>
	<a href="${pageContext.request.contextPath}/domain/user/search" class="ajaxy button button-search"><fmt:message key="user" /></a>
	<a href="${pageContext.request.contextPath}/domain/user/show/${user.primaryKey}" class="ajaxy button button-show"><fmt:message key="crud.show.button" /></a>
	<span class="ui-state-highlight button button-edit"><fmt:message key="crud.edit.button" /></span>
	<a href="${pageContext.request.contextPath}/domain/user/delete/${user.primaryKey}" class="modal button button-delete"><fmt:message key="crud.delete.button" /></a>

	<form:form action="${pageContext.request.contextPath}/domain/user/update/${user.primaryKey}" modelAttribute="user" method="POST">
		<form:errors cssClass="error"/>
		<form:hidden path="userId"/>
		<table class="edit">
			<tbody>
				<tr>
					<th><fmt:message key="user_emailaddress" /> <em>*</em></th>
					<td>
						<form:input path="emailaddress" cssClass="email required {maxlength: 256}" maxlength="256" size="100"/>
						<form:errors path="emailaddress" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="user_password" /> <em>*</em></th>
					<td>
						<form:password path="password" cssClass="required {maxlength: 45}"/>
						<form:errors path="password" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="user_enabled" /> <em>*</em></th>
					<td>
						<form:input path="enabled" cssClass="required {maxlength: 1}" maxlength="1" size="1"/>
						<form:errors path="enabled" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="role" /></th>
					<td>
						<form:select path="roles" multiple="true" items="${roles}" itemValue="primaryKey"/>
						<form:errors cssClass="error" path="roles"/>
					</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">
						<input type="submit" class="button button-save" value="<fmt:message key="crud.save.button" />" />
					</td>
				</tr>
			</tfoot>
		</table>
	</form:form>
</body>
