<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/domain/update.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="photo" />: <fmt:message key="crud.functionalities.update" /></title>
</head>
<body>
	<a href="${pageContext.request.contextPath}/domain/photo/search" class="ajaxy button button-search"><fmt:message key="photo" /></a>
	<a href="${pageContext.request.contextPath}/domain/photo/show/${photo.primaryKey}" class="ajaxy button button-show"><fmt:message key="crud.show.button" /></a>
	<span class="ui-state-highlight button button-edit"><fmt:message key="crud.edit.button" /></span>
	<a href="${pageContext.request.contextPath}/domain/photo/delete/${photo.primaryKey}" class="modal button button-delete"><fmt:message key="crud.delete.button" /></a>

	<form:form action="${pageContext.request.contextPath}/domain/photo/update/${photo.primaryKey}" modelAttribute="photo" method="POST">
		<form:errors cssClass="error"/>
		<form:hidden path="id"/>
		<table class="edit">
			<tbody>
				<tr>
					<th><fmt:message key="photo_name" /></th>
					<td>
						<form:input path="name" cssClass="{maxlength: 26}" maxlength="26" size="30"/>
						<form:errors path="name" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="photo_desc" /></th>
					<td>
						<form:input path="desc" cssClass="{maxlength: 100}" maxlength="100" size="100"/>
						<form:errors path="desc" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="photo_location" /> <em>*</em></th>
					<td>
						<form:input path="location" cssClass="required {maxlength: 256}" maxlength="256" size="100"/>
						<form:errors path="location" cssClass="error"/>
					</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">
						<input type="submit" class="button button-save" value="<fmt:message key="crud.save.button" />" />
					</td>
				</tr>
			</tfoot>
		</table>
	</form:form>
</body>
