<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/domain/namedquery.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><<fmt:message key="role" />: fmt:message key="crud.functionalities.named.query" /></title>
</head>
<body>
	<h2><fmt:message key="role" />: <fmt:message key="crud.functionalities.named.query" /></h2>
	<form:form action="${pageContext.request.contextPath}/domain/role/list" modelAttribute="roleSearchForm" class="search">
		<fieldset>
			<p>
				<label for="sp.namedQuery"><fmt:message key="crud.namedquery" /></label><br>
				<form:input path="sp.namedQuery" cssClass="required" value="Role.selectAll" onclick="this.value='';this.select();"/>
				<p>(ex: Role.selectAll)</p>
			</p>
			<p>
				<input type="submit" class="button button-search" value="<fmt:message key="crud.search.button" />"/>
			</p>
		</fieldset>
	</form:form>
	<div id="result"/>
</body>
