/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateWithRealSessionTest.e.vm.java
 */
package com.mgt.mycity.dao;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.mgt.mycity.domain.Category;
import com.mgt.mycity.service.CategoryGenerator;
import com.mgt.mycity.dao.CategoryDao;
import com.mgt.mycity.util.*;

/**
 * Integration test on CategoryDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class CategoryDaoImplWithRealSessionTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(CategoryDaoImplWithRealSessionTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private CategoryDao categoryDao;

    @Autowired
    private CategoryGenerator categoryGenerator;

    @Before
    public void onSetUp() throws Exception {
        //reset generator
        ValueGenerator.resetAll();
    }

    @Test
    public void testSaveAndGet() {
        Category category = categoryGenerator.getCategory();

        // add it to a Set before saving
        Set<Category> set = new HashSet<Category>();
        set.add(category);

        categoryDao.save(category);
        entityManager.flush();

        // reload it from cache and check equality
        Category model = new Category();
        model.setCategoryId(category.getCategoryId());
        assertThat(category).isEqualTo(categoryDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(category.getPrimaryKey()).isEqualTo(categoryDao.get(model).getPrimaryKey());

        // but since you do not use a business key, equality is lost.
        assertThat(category).isNotEqualTo(categoryDao.get(model));
    }
}