/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateTest.e.vm.java
 */
package com.mgt.mycity.dao;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;

import org.hibernate.Criteria;
import org.hibernate.criterion.Criterion;
import org.hibernate.criterion.Projection;
import org.hibernate.Session;

import com.mgt.mycity.dao.support.NamedQueryUtil;
import com.mgt.mycity.dao.support.SearchTemplate;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import com.mgt.mycity.domain.*;
import com.mgt.mycity.util.*;

/**
 * Unit test on PhotoDaoImpl
 */
public class PhotoDaoImplTest {

    public PhotoDaoImpl photoDao;
    public EntityManager entityManager;
    public Session session;
    public NamedQueryUtil namedQueryUtil;
    public MockCriteriaUtil criteriaUtil;

    @Before
    public void setUp() {
        entityManager = mock(EntityManager.class);
        session = mock(Session.class);
        namedQueryUtil = mock(NamedQueryUtil.class);
        criteriaUtil = new MockCriteriaUtil();

        photoDao = new PhotoDaoImpl();
        photoDao.setEntityManager(entityManager);
        photoDao.setNamedQueryUtil(namedQueryUtil);
    }

    @Test
    public void testGetReturnsNonNullWhenPkIsSet() {
        Photo model = new Photo();
        model.setId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        when(entityManager.find(eq(Photo.class), any())).thenReturn(model);

        Photo result = photoDao.get(model);

        assertThat(result).isNotNull();
        verify(entityManager, times(1)).find(eq(Photo.class), any());
    }

    @Test
    public void testGetReturnsNullWhenPkIsSet() {
        Photo model = new Photo();
        model.setId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        when(entityManager.find(eq(Photo.class), any())).thenReturn(null);

        Photo result = photoDao.get(model);

        assertThat(result).isNull();
        verify(entityManager, times(1)).find(eq(Photo.class), any());
    }

    @Test
    public void testSave() {
        List<Photo> photos = new ArrayList<Photo>();
        photos.add(new Photo());
        photos.add(new Photo());

        photoDao.save(photos);

        verify(entityManager, times(2)).persist(any());
    }

    @Test
    public void testDelete() {
        Photo model1 = new Photo();
        model1.setId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        Photo model2 = new Photo();
        model2.setId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        List<Photo> photos = new ArrayList<Photo>();
        photos.add(model1);
        photos.add(model2);

        when(entityManager.contains(any())).thenReturn(true);

        photoDao.delete(photos);

        verify(entityManager, times(2)).remove(any());
    }

    @Test
    public void testFindUseNamedQueryUtil() {
        Photo model = new Photo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");
        List<Photo> photos = new ArrayList<Photo>();

        when(namedQueryUtil.findByNamedQuery(any(SearchTemplate.class), any())).thenReturn((List) photos);

        List<Photo> result = photoDao.find(model, searchTemplate);

        assertThat(result).isSameAs(photos);
        verify(namedQueryUtil, times(1)).findByNamedQuery(any(SearchTemplate.class), any());

    }

    @Test
    public void testFindCountUseNamedQueryUtil() {
        final int expectedResult = 10;
        Photo model = new Photo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");

        when(namedQueryUtil.numberByNamedQuery(any(SearchTemplate.class), any())).thenReturn(expectedResult);

        int result = photoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(namedQueryUtil, times(1)).numberByNamedQuery(any(SearchTemplate.class), any());
    }

    @Test
    public void testFindCountCaseNullResultCriteria() {
        Photo model = new Photo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, Photo.class);
        when(criteria.uniqueResult()).thenReturn(null);

        int result = photoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(0);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testFindCountCaseNotNullResultCriteria() {
        final int expectedResult = 10;
        Photo model = new Photo();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, Photo.class);
        when(criteria.uniqueResult()).thenReturn(expectedResult);

        int result = photoDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testGetLocalSearchTemplateWithNullSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        photoDao.setCacheable(cacheable);
        photoDao.setCacheRegion(cacheRegion);

        SearchTemplate result = photoDao.getLocalSearchTemplate(null);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithDefaultSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        photoDao.setCacheable(cacheable);
        photoDao.setCacheRegion(cacheRegion);
        SearchTemplate defaultSearchTemplate = new SearchTemplate().setCacheable(null);

        SearchTemplate result = photoDao.getLocalSearchTemplate(defaultSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithNormalSearchTemplate() {
        String normalCacheRegion = "normalcacheRegion";
        boolean normalCacheable = false;
        photoDao.setCacheable(true);
        photoDao.setCacheRegion("cacheRegion");

        SearchTemplate normalSearchTemplate = new SearchTemplate();
        normalSearchTemplate.setCacheable(normalCacheable);
        normalSearchTemplate.setCacheRegion(normalCacheRegion);

        SearchTemplate result = photoDao.getLocalSearchTemplate(normalSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(normalCacheRegion);
        assertThat(result.isCacheable()).isEqualTo(normalCacheable);
    }
}