/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateWithRealSessionTest.e.vm.java
 */
package com.mgt.mycity.dao;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.mgt.mycity.domain.Photo;
import com.mgt.mycity.service.PhotoGenerator;
import com.mgt.mycity.dao.PhotoDao;
import com.mgt.mycity.util.*;

/**
 * Integration test on PhotoDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class PhotoDaoImplWithRealSessionTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(PhotoDaoImplWithRealSessionTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private PhotoDao photoDao;

    @Autowired
    private PhotoGenerator photoGenerator;

    @Before
    public void onSetUp() throws Exception {
        //reset generator
        ValueGenerator.resetAll();
    }

    @Test
    public void testSaveAndGet() {
        Photo photo = photoGenerator.getPhoto();

        // add it to a Set before saving
        Set<Photo> set = new HashSet<Photo>();
        set.add(photo);

        photoDao.save(photo);
        entityManager.flush();

        // reload it from cache and check equality
        Photo model = new Photo();
        model.setId(photo.getId());
        assertThat(photo).isEqualTo(photoDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(photo.getPrimaryKey()).isEqualTo(photoDao.get(model).getPrimaryKey());

        // but since you do not use a business key, equality is lost.
        assertThat(photo).isNotEqualTo(photoDao.get(model));
    }
}