/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateTest.e.vm.java
 */
package com.mgt.mycity.dao;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.EntityManager;

import org.hibernate.Criteria;
import org.hibernate.criterion.Criterion;
import org.hibernate.criterion.Projection;
import org.hibernate.Session;

import com.mgt.mycity.dao.support.NamedQueryUtil;
import com.mgt.mycity.dao.support.SearchTemplate;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import com.mgt.mycity.domain.*;
import com.mgt.mycity.util.*;

/**
 * Unit test on RestaurentDaoImpl
 */
public class RestaurentDaoImplTest {

    public RestaurentDaoImpl restaurentDao;
    public EntityManager entityManager;
    public Session session;
    public NamedQueryUtil namedQueryUtil;
    public MockCriteriaUtil criteriaUtil;

    @Before
    public void setUp() {
        entityManager = mock(EntityManager.class);
        session = mock(Session.class);
        namedQueryUtil = mock(NamedQueryUtil.class);
        criteriaUtil = new MockCriteriaUtil();

        restaurentDao = new RestaurentDaoImpl();
        restaurentDao.setEntityManager(entityManager);
        restaurentDao.setNamedQueryUtil(namedQueryUtil);
    }

    @Test
    public void testGetReturnsNonNullWhenPkIsSet() {
        Restaurent model = new Restaurent();
        model.setRestaurentId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        when(entityManager.find(eq(Restaurent.class), any())).thenReturn(model);

        Restaurent result = restaurentDao.get(model);

        assertThat(result).isNotNull();
        verify(entityManager, times(1)).find(eq(Restaurent.class), any());
    }

    @Test
    public void testGetReturnsNullWhenPkIsSet() {
        Restaurent model = new Restaurent();
        model.setRestaurentId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        when(entityManager.find(eq(Restaurent.class), any())).thenReturn(null);

        Restaurent result = restaurentDao.get(model);

        assertThat(result).isNull();
        verify(entityManager, times(1)).find(eq(Restaurent.class), any());
    }

    @Test
    public void testSave() {
        List<Restaurent> restaurents = new ArrayList<Restaurent>();
        restaurents.add(new Restaurent());
        restaurents.add(new Restaurent());

        restaurentDao.save(restaurents);

        verify(entityManager, times(2)).persist(any());
    }

    @Test
    public void testDelete() {
        Restaurent model1 = new Restaurent();
        model1.setRestaurentId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        Restaurent model2 = new Restaurent();
        model2.setRestaurentId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));

        List<Restaurent> restaurents = new ArrayList<Restaurent>();
        restaurents.add(model1);
        restaurents.add(model2);

        when(entityManager.contains(any())).thenReturn(true);

        restaurentDao.delete(restaurents);

        verify(entityManager, times(2)).remove(any());
    }

    @Test
    public void testFindUseNamedQueryUtil() {
        Restaurent model = new Restaurent();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");
        List<Restaurent> restaurents = new ArrayList<Restaurent>();

        when(namedQueryUtil.findByNamedQuery(any(SearchTemplate.class), any())).thenReturn((List) restaurents);

        List<Restaurent> result = restaurentDao.find(model, searchTemplate);

        assertThat(result).isSameAs(restaurents);
        verify(namedQueryUtil, times(1)).findByNamedQuery(any(SearchTemplate.class), any());

    }

    @Test
    public void testFindCountUseNamedQueryUtil() {
        final int expectedResult = 10;
        Restaurent model = new Restaurent();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setNamedQuery("myNamedQuery");

        when(namedQueryUtil.numberByNamedQuery(any(SearchTemplate.class), any())).thenReturn(expectedResult);

        int result = restaurentDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(namedQueryUtil, times(1)).numberByNamedQuery(any(SearchTemplate.class), any());
    }

    @Test
    public void testFindCountCaseNullResultCriteria() {
        Restaurent model = new Restaurent();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, Restaurent.class);
        when(criteria.uniqueResult()).thenReturn(null);

        int result = restaurentDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(0);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testFindCountCaseNotNullResultCriteria() {
        final int expectedResult = 10;
        Restaurent model = new Restaurent();
        SearchTemplate searchTemplate = new SearchTemplate();
        searchTemplate.setCacheable(false);

        Criteria criteria = criteriaUtil.prepareThenReturnCriteria(entityManager, session, Restaurent.class);
        when(criteria.uniqueResult()).thenReturn(expectedResult);

        int result = restaurentDao.findCount(model, searchTemplate);

        assertThat(result).isEqualTo(expectedResult);
        verify(criteria, times(1)).uniqueResult();
    }

    @Test
    public void testGetLocalSearchTemplateWithNullSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        restaurentDao.setCacheable(cacheable);
        restaurentDao.setCacheRegion(cacheRegion);

        SearchTemplate result = restaurentDao.getLocalSearchTemplate(null);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithDefaultSearchTemplate() {
        String cacheRegion = "cacheRegion";
        boolean cacheable = true;
        restaurentDao.setCacheable(cacheable);
        restaurentDao.setCacheRegion(cacheRegion);
        SearchTemplate defaultSearchTemplate = new SearchTemplate().setCacheable(null);

        SearchTemplate result = restaurentDao.getLocalSearchTemplate(defaultSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(cacheRegion);
        assertThat(result.isCacheable()).isEqualTo(cacheable);
    }

    @Test
    public void testGetLocalSearchTemplateWithNormalSearchTemplate() {
        String normalCacheRegion = "normalcacheRegion";
        boolean normalCacheable = false;
        restaurentDao.setCacheable(true);
        restaurentDao.setCacheRegion("cacheRegion");

        SearchTemplate normalSearchTemplate = new SearchTemplate();
        normalSearchTemplate.setCacheable(normalCacheable);
        normalSearchTemplate.setCacheRegion(normalCacheRegion);

        SearchTemplate result = restaurentDao.getLocalSearchTemplate(normalSearchTemplate);

        assertThat(result.getCacheRegion()).isEqualTo(normalCacheRegion);
        assertThat(result.isCacheable()).isEqualTo(normalCacheable);
    }
}