/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateWithRealSessionTest.e.vm.java
 */
package com.mgt.mycity.dao;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.mgt.mycity.domain.Restaurent;
import com.mgt.mycity.service.RestaurentGenerator;
import com.mgt.mycity.dao.RestaurentDao;
import com.mgt.mycity.util.*;

/**
 * Integration test on RestaurentDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class RestaurentDaoImplWithRealSessionTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(RestaurentDaoImplWithRealSessionTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private RestaurentDao restaurentDao;

    @Autowired
    private RestaurentGenerator restaurentGenerator;

    @Before
    public void onSetUp() throws Exception {
        //reset generator
        ValueGenerator.resetAll();
    }

    @Test
    public void testSaveAndGet() {
        Restaurent restaurent = restaurentGenerator.getRestaurent();

        // add it to a Set before saving
        Set<Restaurent> set = new HashSet<Restaurent>();
        set.add(restaurent);

        restaurentDao.save(restaurent);
        entityManager.flush();

        // reload it from cache and check equality
        Restaurent model = new Restaurent();
        model.setRestaurentId(restaurent.getRestaurentId());
        assertThat(restaurent).isEqualTo(restaurentDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(restaurent.getPrimaryKey()).isEqualTo(restaurentDao.get(model).getPrimaryKey());

        // but since you do not use a business key, equality is lost.
        assertThat(restaurent).isNotEqualTo(restaurentDao.get(model));
    }
}