/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/hibernate/DAOHibernateWithRealSessionTest.e.vm.java
 */
package com.mgt.mycity.dao;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.apache.log4j.Logger;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.mgt.mycity.domain.User;
import com.mgt.mycity.service.UserGenerator;
import com.mgt.mycity.dao.UserDao;
import com.mgt.mycity.util.*;

/**
 * Integration test on UserDaoImpl
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class UserDaoImplWithRealSessionTest {
    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(UserDaoImplWithRealSessionTest.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Autowired
    private UserDao userDao;

    @Autowired
    private UserGenerator userGenerator;

    @Before
    public void onSetUp() throws Exception {
        //reset generator
        ValueGenerator.resetAll();
    }

    @Test
    public void testSaveAndGet() {
        User user = userGenerator.getUser();

        // add it to a Set before saving
        Set<User> set = new HashSet<User>();
        set.add(user);

        userDao.save(user);
        entityManager.flush();

        // reload it from cache and check equality
        User model = new User();
        model.setUserId(user.getUserId());
        assertThat(user).isEqualTo(userDao.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(user.getPrimaryKey()).isEqualTo(userDao.get(model).getPrimaryKey());

        // but since you do not use a business key, equality is lost.
        assertThat(user).isNotEqualTo(userDao.get(model));
    }
}