/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/dao/DAO.e.vm.java
 */
package com.mgt.mycity.dao;

import com.mgt.mycity.dao.support.GenericDao;
import com.mgt.mycity.domain.Photo;

/**
 * DAO Interface for {@link Photo}
 */
public interface PhotoDao extends GenericDao<Photo, Integer> {
}
