/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.mgt.mycity.dao;

import org.hibernate.Criteria;
import org.springframework.stereotype.Repository;
import com.mgt.mycity.dao.RestaurentDao;
import com.mgt.mycity.dao.hibernate.HibernateUtil;
import com.mgt.mycity.dao.support.SearchTemplate;
import com.mgt.mycity.domain.Restaurent;

import com.mgt.mycity.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the {@link RestaurentDao} interface.
 */
@Repository
public class RestaurentDaoImpl extends HibernateGenericDao<Restaurent, Integer> implements RestaurentDao {
    public RestaurentDaoImpl() {
        super(Restaurent.class);
    }

    /**
     * Constructs the search by example criteria using not only the passed {@link Restaurent} but also its associated entities. 
     */
    @Override
    public Criteria getCriteria(Restaurent restaurent, SearchTemplate searchTemplate) {
        // Call super to construct the criteria of the 'root' entity.
        Criteria criteria = super.getCriteria(restaurent, searchTemplate);
        HibernateUtil.applyToOneAssociationOnCriteria(criteria, searchTemplate, "photo", restaurent.getPhotoId(),
                restaurent.getPhoto());
        HibernateUtil.applyToManyAssociationOnCriteria(criteria, searchTemplate, "categories", restaurent
                .getCategories());
        return criteria;
    }
}