/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/hibernate/DAOHibernate.e.vm.java
 */
package com.mgt.mycity.dao;

import org.hibernate.Criteria;
import org.springframework.stereotype.Repository;
import com.mgt.mycity.dao.UserDao;
import com.mgt.mycity.dao.hibernate.HibernateUtil;
import com.mgt.mycity.dao.support.SearchTemplate;
import com.mgt.mycity.domain.User;

import com.mgt.mycity.dao.hibernate.HibernateGenericDao;

/**
 * Hibernate implementation of the {@link UserDao} interface.
 */
@Repository
public class UserDaoImpl extends HibernateGenericDao<User, Integer> implements UserDao {
    public UserDaoImpl() {
        super(User.class);
    }

    /**
     * Constructs the search by example criteria using not only the passed {@link User} but also its associated entities. 
     */
    @Override
    public Criteria getCriteria(User user, SearchTemplate searchTemplate) {
        // Call super to construct the criteria of the 'root' entity.
        Criteria criteria = super.getCriteria(user, searchTemplate);
        HibernateUtil.applyToManyAssociationOnCriteria(criteria, searchTemplate, "roles", user.getRoles());
        return criteria;
    }
}