/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/Formatter.e.vm.java
 */
package com.mgt.mycity.formatter;

import java.text.ParseException;
import java.util.Locale;

import com.mgt.mycity.domain.Restaurent;
import com.mgt.mycity.service.RestaurentService;
import com.mgt.mycity.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link Restaurent} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 * 
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class RestaurentFormatter implements DiscoverableFormatter<Restaurent> {

    @Autowired
    private RestaurentService restaurentService;

    @Override
    public Class<Restaurent> getTarget() {
        return Restaurent.class;
    }

    @Override
    public String print(Restaurent restaurent, Locale locale) {
        if (restaurent == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (restaurent.getCode() != null) {
            sb.append(restaurent.getCode()).append(" ");
        }

        if (restaurent.getName() != null) {
            sb.append(restaurent.getName()).append(" ");
        }

        if (restaurent.getDesc() != null) {
            sb.append(restaurent.getDesc()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (restaurent.isPrimaryKeySet()) {
            return restaurent.getPrimaryKey().toString();
        } else {
            return restaurent.toString();
        }
    }

    @Override
    public Restaurent parse(String text, Locale locale) throws ParseException {
        if (text == null || text.isEmpty()) {
            return new Restaurent();
        }
        Restaurent restaurent = restaurentService.getByPrimaryKey(new Integer(text));
        return restaurent != null ? restaurent : new Restaurent();
    }
}
