/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/formatter/Formatter.e.vm.java
 */
package com.mgt.mycity.formatter;

import java.text.ParseException;
import java.util.Locale;

import com.mgt.mycity.domain.Role;
import com.mgt.mycity.service.RoleService;
import com.mgt.mycity.formatter.support.DiscoverableFormatter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * {@link Formatter} for {@link Role} that is picked by automatically by {@link CustomFormattingConversionServiceFactory}
 * 
 * @see Formatter
 * @see CustomFormattingConversionServiceFactory
 */
@Component
public class RoleFormatter implements DiscoverableFormatter<Role> {

    @Autowired
    private RoleService roleService;

    @Override
    public Class<Role> getTarget() {
        return Role.class;
    }

    @Override
    public String print(Role role, Locale locale) {
        if (role == null) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        // make a nice display string here...

        if (role.getRoleName() != null) {
            sb.append(role.getRoleName()).append(" ");
        }

        if (sb.length() > 0) {
            return sb.toString();
        } else if (role.isPrimaryKeySet()) {
            return role.getPrimaryKey().toString();
        } else {
            return role.toString();
        }
    }

    @Override
    public Role parse(String text, Locale locale) throws ParseException {
        if (text == null || text.isEmpty()) {
            return new Role();
        }
        Role role = roleService.getByPrimaryKey(new Integer(text));
        return role != null ? role : new Role();
    }
}
