/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ManagerImplTest.e.vm.java
 */
package com.mgt.mycity.service;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.InvalidDataAccessApiUsageException;

import com.mgt.mycity.domain.Category;
import com.mgt.mycity.service.CategoryServiceImpl;
import com.mgt.mycity.dao.CategoryDao;
import com.mgt.mycity.dao.support.SearchTemplate;

/**
 * Unit test on CategoryServiceImpl
 */
public class CategoryServiceImplTest {

    private CategoryServiceImpl categoryServiceImpl;
    private CategoryDao categoryDao;

    @Before
    public void setUp() {
        // called before each test.
        categoryServiceImpl = new CategoryServiceImpl();
        categoryDao = mock(CategoryDao.class);
        categoryServiceImpl.setCategoryDao(categoryDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        List<Category> none = new ArrayList<Category>();

        when(categoryDao.find(any(Category.class), any(SearchTemplate.class))).thenReturn(none);

        Category result = categoryServiceImpl.findUniqueOrNone(new Category());

        assertThat(result).isNull();
        verify(categoryDao, times(1)).find(any(Category.class), any(SearchTemplate.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        List<Category> unique = new ArrayList<Category>();
        unique.add(new Category());

        when(categoryDao.find(any(Category.class), any(SearchTemplate.class))).thenReturn(unique);

        Category result = categoryServiceImpl.findUniqueOrNone(new Category());

        assertThat(result).isNotNull();
        verify(categoryDao, times(1)).find(any(Category.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        List<Category> multiple = new ArrayList<Category>();
        multiple.add(new Category());
        multiple.add(new Category());

        when(categoryDao.find(any(Category.class), any(SearchTemplate.class))).thenReturn(multiple);

        categoryServiceImpl.findUniqueOrNone(new Category());
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseNone() {
        List<Category> none = new ArrayList<Category>();

        when(categoryDao.find(any(Category.class), any(SearchTemplate.class))).thenReturn(none);

        categoryServiceImpl.findUnique(new Category());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        List<Category> unique = new ArrayList<Category>();
        unique.add(new Category());

        when(categoryDao.find(any(Category.class), any(SearchTemplate.class))).thenReturn(unique);

        Category result = categoryServiceImpl.findUnique(new Category());

        assertThat(result).isNotNull();
        verify(categoryDao, times(1)).find(any(Category.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseMultiple() {
        List<Category> multiple = new ArrayList<Category>();
        multiple.add(new Category());
        multiple.add(new Category());

        when(categoryDao.find(any(Category.class), any(SearchTemplate.class))).thenReturn(multiple);

        categoryServiceImpl.findUnique(new Category());
    }
}