/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ManagerImplTest.e.vm.java
 */
package com.mgt.mycity.service;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.InvalidDataAccessApiUsageException;

import com.mgt.mycity.domain.Photo;
import com.mgt.mycity.service.PhotoServiceImpl;
import com.mgt.mycity.dao.PhotoDao;
import com.mgt.mycity.dao.support.SearchTemplate;

/**
 * Unit test on PhotoServiceImpl
 */
public class PhotoServiceImplTest {

    private PhotoServiceImpl photoServiceImpl;
    private PhotoDao photoDao;

    @Before
    public void setUp() {
        // called before each test.
        photoServiceImpl = new PhotoServiceImpl();
        photoDao = mock(PhotoDao.class);
        photoServiceImpl.setPhotoDao(photoDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        List<Photo> none = new ArrayList<Photo>();

        when(photoDao.find(any(Photo.class), any(SearchTemplate.class))).thenReturn(none);

        Photo result = photoServiceImpl.findUniqueOrNone(new Photo());

        assertThat(result).isNull();
        verify(photoDao, times(1)).find(any(Photo.class), any(SearchTemplate.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        List<Photo> unique = new ArrayList<Photo>();
        unique.add(new Photo());

        when(photoDao.find(any(Photo.class), any(SearchTemplate.class))).thenReturn(unique);

        Photo result = photoServiceImpl.findUniqueOrNone(new Photo());

        assertThat(result).isNotNull();
        verify(photoDao, times(1)).find(any(Photo.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        List<Photo> multiple = new ArrayList<Photo>();
        multiple.add(new Photo());
        multiple.add(new Photo());

        when(photoDao.find(any(Photo.class), any(SearchTemplate.class))).thenReturn(multiple);

        photoServiceImpl.findUniqueOrNone(new Photo());
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseNone() {
        List<Photo> none = new ArrayList<Photo>();

        when(photoDao.find(any(Photo.class), any(SearchTemplate.class))).thenReturn(none);

        photoServiceImpl.findUnique(new Photo());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        List<Photo> unique = new ArrayList<Photo>();
        unique.add(new Photo());

        when(photoDao.find(any(Photo.class), any(SearchTemplate.class))).thenReturn(unique);

        Photo result = photoServiceImpl.findUnique(new Photo());

        assertThat(result).isNotNull();
        verify(photoDao, times(1)).find(any(Photo.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseMultiple() {
        List<Photo> multiple = new ArrayList<Photo>();
        multiple.add(new Photo());
        multiple.add(new Photo());

        when(photoDao.find(any(Photo.class), any(SearchTemplate.class))).thenReturn(multiple);

        photoServiceImpl.findUnique(new Photo());
    }
}