/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ManagerImplTest.e.vm.java
 */
package com.mgt.mycity.service;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.InvalidDataAccessApiUsageException;

import com.mgt.mycity.domain.Restaurent;
import com.mgt.mycity.service.RestaurentServiceImpl;
import com.mgt.mycity.dao.RestaurentDao;
import com.mgt.mycity.dao.support.SearchTemplate;

/**
 * Unit test on RestaurentServiceImpl
 */
public class RestaurentServiceImplTest {

    private RestaurentServiceImpl restaurentServiceImpl;
    private RestaurentDao restaurentDao;

    @Before
    public void setUp() {
        // called before each test.
        restaurentServiceImpl = new RestaurentServiceImpl();
        restaurentDao = mock(RestaurentDao.class);
        restaurentServiceImpl.setRestaurentDao(restaurentDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        List<Restaurent> none = new ArrayList<Restaurent>();

        when(restaurentDao.find(any(Restaurent.class), any(SearchTemplate.class))).thenReturn(none);

        Restaurent result = restaurentServiceImpl.findUniqueOrNone(new Restaurent());

        assertThat(result).isNull();
        verify(restaurentDao, times(1)).find(any(Restaurent.class), any(SearchTemplate.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        List<Restaurent> unique = new ArrayList<Restaurent>();
        unique.add(new Restaurent());

        when(restaurentDao.find(any(Restaurent.class), any(SearchTemplate.class))).thenReturn(unique);

        Restaurent result = restaurentServiceImpl.findUniqueOrNone(new Restaurent());

        assertThat(result).isNotNull();
        verify(restaurentDao, times(1)).find(any(Restaurent.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        List<Restaurent> multiple = new ArrayList<Restaurent>();
        multiple.add(new Restaurent());
        multiple.add(new Restaurent());

        when(restaurentDao.find(any(Restaurent.class), any(SearchTemplate.class))).thenReturn(multiple);

        restaurentServiceImpl.findUniqueOrNone(new Restaurent());
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseNone() {
        List<Restaurent> none = new ArrayList<Restaurent>();

        when(restaurentDao.find(any(Restaurent.class), any(SearchTemplate.class))).thenReturn(none);

        restaurentServiceImpl.findUnique(new Restaurent());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        List<Restaurent> unique = new ArrayList<Restaurent>();
        unique.add(new Restaurent());

        when(restaurentDao.find(any(Restaurent.class), any(SearchTemplate.class))).thenReturn(unique);

        Restaurent result = restaurentServiceImpl.findUnique(new Restaurent());

        assertThat(result).isNotNull();
        verify(restaurentDao, times(1)).find(any(Restaurent.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseMultiple() {
        List<Restaurent> multiple = new ArrayList<Restaurent>();
        multiple.add(new Restaurent());
        multiple.add(new Restaurent());

        when(restaurentDao.find(any(Restaurent.class), any(SearchTemplate.class))).thenReturn(multiple);

        restaurentServiceImpl.findUnique(new Restaurent());
    }
}