/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/manager/ManagerImplTest.e.vm.java
 */
package com.mgt.mycity.service;

import static org.fest.assertions.Assertions.*;
import static org.mockito.Matchers.*;
import static org.mockito.Mockito.*;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.InvalidDataAccessApiUsageException;

import com.mgt.mycity.domain.User;
import com.mgt.mycity.service.UserServiceImpl;
import com.mgt.mycity.dao.UserDao;
import com.mgt.mycity.dao.support.SearchTemplate;

/**
 * Unit test on UserServiceImpl
 */
public class UserServiceImplTest {

    private UserServiceImpl userServiceImpl;
    private UserDao userDao;

    @Before
    public void setUp() {
        // called before each test.
        userServiceImpl = new UserServiceImpl();
        userDao = mock(UserDao.class);
        userServiceImpl.setUserDao(userDao);
    }

    @Test
    public void testFindUniqueOrNoneCaseNone() {
        List<User> none = new ArrayList<User>();

        when(userDao.find(any(User.class), any(SearchTemplate.class))).thenReturn(none);

        User result = userServiceImpl.findUniqueOrNone(new User());

        assertThat(result).isNull();
        verify(userDao, times(1)).find(any(User.class), any(SearchTemplate.class));
    }

    @Test
    public void testFindUniqueOrNoneCaseUnique() {
        List<User> unique = new ArrayList<User>();
        unique.add(new User());

        when(userDao.find(any(User.class), any(SearchTemplate.class))).thenReturn(unique);

        User result = userServiceImpl.findUniqueOrNone(new User());

        assertThat(result).isNotNull();
        verify(userDao, times(1)).find(any(User.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueOrNoneCaseMultiple() {
        List<User> multiple = new ArrayList<User>();
        multiple.add(new User());
        multiple.add(new User());

        when(userDao.find(any(User.class), any(SearchTemplate.class))).thenReturn(multiple);

        userServiceImpl.findUniqueOrNone(new User());
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseNone() {
        List<User> none = new ArrayList<User>();

        when(userDao.find(any(User.class), any(SearchTemplate.class))).thenReturn(none);

        userServiceImpl.findUnique(new User());
    }

    @Test
    public void testFindUniqueCaseUnique() {
        List<User> unique = new ArrayList<User>();
        unique.add(new User());

        when(userDao.find(any(User.class), any(SearchTemplate.class))).thenReturn(unique);

        User result = userServiceImpl.findUnique(new User());

        assertThat(result).isNotNull();
        verify(userDao, times(1)).find(any(User.class), any(SearchTemplate.class));
    }

    @Test(expected = InvalidDataAccessApiUsageException.class)
    public void testFindUniqueCaseMultiple() {
        List<User> multiple = new ArrayList<User>();
        multiple.add(new User());
        multiple.add(new User());

        when(userDao.find(any(User.class), any(SearchTemplate.class))).thenReturn(multiple);

        userServiceImpl.findUnique(new User());
    }
}