/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/controller.e.vm.java
 */
package com.mgt.mycity.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import com.mgt.mycity.domain.Category;
import com.mgt.mycity.service.CategoryService;

@Controller
@RequestMapping("/domain/category/")
public class CategoryController {

    @Autowired
    private CategoryService categoryService;

    /**
     * Performs the list action.
     */
    @RequestMapping(value = { "list", "" })
    public String list(@ModelAttribute CategorySearchForm categorySearchForm, Model model) {
        model.addAttribute("categoriesCount", categoryService.findCount(categorySearchForm.getCategory(),
                categorySearchForm.toSearchTemplate()));
        model.addAttribute("categories", categoryService.find(categorySearchForm.getCategory(), categorySearchForm
                .toSearchTemplate()));
        return "domain/category/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute Category category) {
        return "domain/category/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute Category category, BindingResult bindingResult) {
        if (bindingResult.hasErrors()) {
            return create(category);
        }

        categoryService.save(category);
        return "redirect:/domain/category/show/" + category.getPrimaryKey();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute CategorySearchForm categorySearchForm) {
    }

}