/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/restController.e.vm.java
 */
package com.mgt.mycity.web.controller;

import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.mgt.mycity.web.util.AutoCompleteResult;
import com.mgt.mycity.web.util.SearchParameters;
import com.mgt.mycity.domain.Category;
import com.mgt.mycity.service.CategoryService;

@Controller
@RequestMapping("domain/rest/category/")
public class CategoryRestController {
    @Autowired
    public FormattingConversionService formattingConversionService;

    @Autowired
    private CategoryService categoryService;

    @RequestMapping(value = "/", method = POST)
    @ResponseBody
    public Category create(@Valid Category category) {
        categoryService.save(category);
        return category.copy();
    }

    @RequestMapping(value = "/", method = POST, headers = "content-type:application/json")
    @ResponseBody
    public Category jsonCreate(@Valid @RequestBody Category category) {
        categoryService.save(category);
        return category.copy();
    }

    @RequestMapping(value = "/", method = GET)
    @ResponseBody
    public List<Category> list(Category category, SearchParameters searchParameters) {
        List<Category> categories = categoryService.find(category, searchParameters.toSearchTemplate());
        List<Category> ret = new ArrayList<Category>();
        for (Category _category : categories) {
            ret.add(_category.copy());
        }
        return ret;
    }

    @RequestMapping(value = "/{pk}", method = GET)
    @ResponseBody
    public Category get(@PathVariable("pk") Category category) {
        return category.copy();
    }

    @RequestMapping(value = "/{pk}", method = PUT)
    @ResponseBody
    public Category update(@PathVariable("pk") Category categoryToUpdate, @Valid Category category) {
        category.copyTo(categoryToUpdate);
        categoryService.save(categoryToUpdate);
        return categoryToUpdate.copy();
    }

    @RequestMapping(value = "/{pk}", method = DELETE)
    @ResponseBody
    public boolean delete(@PathVariable("pk") Category category) {
        categoryService.delete(category);
        return true;
    }

    @RequestMapping("/autocomplete")
    @ResponseBody
    public List<AutoCompleteResult> autocomplete(@RequestParam(value = "term", required = false) String searchPattern,
            SearchParameters search) {
        if (searchPattern != null && !searchPattern.isEmpty()) {
            search.setSearchPattern(searchPattern);
        }
        List<AutoCompleteResult> ret = new ArrayList<AutoCompleteResult>();
        for (Category category : categoryService.find(search.toSearchTemplate())) {
            String objectPk = category.getPrimaryKey().toString();
            String objectLabel = formattingConversionService.convert(category, String.class);
            ret.add(new AutoCompleteResult(objectPk, objectLabel));
        }
        return ret;
    }

    @ExceptionHandler()
    @ResponseStatus(value = INTERNAL_SERVER_ERROR)
    public void exception(Exception e, PrintWriter out) {
        out.write(e.getMessage());
    }
}