/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/restController.e.vm.java
 */
package com.mgt.mycity.web.controller;

import static org.springframework.http.HttpStatus.INTERNAL_SERVER_ERROR;
import static org.springframework.web.bind.annotation.RequestMethod.DELETE;
import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

import com.mgt.mycity.web.util.AutoCompleteResult;
import com.mgt.mycity.web.util.SearchParameters;
import com.mgt.mycity.domain.Photo;
import com.mgt.mycity.service.PhotoService;

@Controller
@RequestMapping("domain/rest/photo/")
public class PhotoRestController {
    @Autowired
    public FormattingConversionService formattingConversionService;

    @Autowired
    private PhotoService photoService;

    @RequestMapping(value = "/", method = POST)
    @ResponseBody
    public Photo create(@Valid Photo photo) {
        photoService.save(photo);
        return photo.copy();
    }

    @RequestMapping(value = "/", method = POST, headers = "content-type:application/json")
    @ResponseBody
    public Photo jsonCreate(@Valid @RequestBody Photo photo) {
        photoService.save(photo);
        return photo.copy();
    }

    @RequestMapping(value = "/", method = GET)
    @ResponseBody
    public List<Photo> list(Photo photo, SearchParameters searchParameters) {
        List<Photo> photos = photoService.find(photo, searchParameters.toSearchTemplate());
        List<Photo> ret = new ArrayList<Photo>();
        for (Photo _photo : photos) {
            ret.add(_photo.copy());
        }
        return ret;
    }

    @RequestMapping(value = "/{pk}", method = GET)
    @ResponseBody
    public Photo get(@PathVariable("pk") Photo photo) {
        return photo.copy();
    }

    @RequestMapping(value = "/{pk}", method = PUT)
    @ResponseBody
    public Photo update(@PathVariable("pk") Photo photoToUpdate, @Valid Photo photo) {
        photo.copyTo(photoToUpdate);
        photoService.save(photoToUpdate);
        return photoToUpdate.copy();
    }

    @RequestMapping(value = "/{pk}", method = DELETE)
    @ResponseBody
    public boolean delete(@PathVariable("pk") Photo photo) {
        photoService.delete(photo);
        return true;
    }

    @RequestMapping("/autocomplete")
    @ResponseBody
    public List<AutoCompleteResult> autocomplete(@RequestParam(value = "term", required = false) String searchPattern,
            SearchParameters search) {
        if (searchPattern != null && !searchPattern.isEmpty()) {
            search.setSearchPattern(searchPattern);
        }
        List<AutoCompleteResult> ret = new ArrayList<AutoCompleteResult>();
        for (Photo photo : photoService.find(search.toSearchTemplate())) {
            String objectPk = photo.getPrimaryKey().toString();
            String objectLabel = formattingConversionService.convert(photo, String.class);
            ret.add(new AutoCompleteResult(objectPk, objectLabel));
        }
        return ret;
    }

    @ExceptionHandler()
    @ResponseStatus(value = INTERNAL_SERVER_ERROR)
    public void exception(Exception e, PrintWriter out) {
        out.write(e.getMessage());
    }
}