/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/controller.e.vm.java
 */
package com.mgt.mycity.web.controller;

import static org.springframework.web.bind.annotation.RequestMethod.GET;
import static org.springframework.web.bind.annotation.RequestMethod.POST;
import static org.springframework.web.bind.annotation.RequestMethod.PUT;

import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;

import com.mgt.mycity.domain.Restaurent;
import com.mgt.mycity.service.RestaurentService;
import com.mgt.mycity.domain.Category;
import com.mgt.mycity.service.CategoryService;

@Controller
@RequestMapping("/domain/restaurent/")
public class RestaurentController {

    @Autowired
    private RestaurentService restaurentService;
    @Autowired
    private CategoryService categoryService;

    /**
     * Performs the list action.
     */
    @RequestMapping(value = { "list", "" })
    public String list(@ModelAttribute RestaurentSearchForm restaurentSearchForm, Model model) {
        model.addAttribute("restaurentsCount", restaurentService.findCount(restaurentSearchForm.getRestaurent(),
                restaurentSearchForm.toSearchTemplate()));
        model.addAttribute("restaurents", restaurentService.find(restaurentSearchForm.getRestaurent(),
                restaurentSearchForm.toSearchTemplate()));
        return "domain/restaurent/list";
    }

    /**
     * Serves the create form.
     */
    @RequestMapping(value = "create", method = GET)
    public String create(@ModelAttribute Restaurent restaurent, Model model) {
        bindListForSelectInputFields(model);
        return "domain/restaurent/create";
    }

    /**
     * Performs the create action and redirect to the show view.
     */
    @RequestMapping(value = "create", method = { POST, PUT })
    public String create(@Valid @ModelAttribute Restaurent restaurent, BindingResult bindingResult, Model model) {
        if (bindingResult.hasErrors()) {
            return create(restaurent, model);
        }

        restaurentService.save(restaurent);
        return "redirect:/domain/restaurent/show/" + restaurent.getPrimaryKey();
    }

    /**
     * Serves search by example form, search by pattern form and search by named query form.
     */
    @RequestMapping(value = "*", method = GET)
    public void catchAll(@ModelAttribute RestaurentSearchForm restaurentSearchForm, Model model) {
        bindListForSelectInputFields(model);
    }

    /**
     * Binds to the passed model the possible values for select input fields.
     */
    private void bindListForSelectInputFields(Model model) {
        model.addAttribute("categories", categoryService.find());
    }
}