/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-mvc-3:src/main/java/web/controller/SearchForm.e.vm.java
 */
package com.mgt.mycity.web.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.mgt.mycity.dao.support.DateRange;
import com.mgt.mycity.web.util.DateRangeUtil;
import com.mgt.mycity.domain.Restaurent;
import com.mgt.mycity.web.util.SearchForm;
import com.mgt.mycity.web.util.NullRestriction;

/**
 * SearchForm for {@link RestaurentService}
 */
public class RestaurentSearchForm extends SearchForm implements Serializable {
    private static final long serialVersionUID = 1L;
    private Restaurent restaurent = new Restaurent();

    /**
     * The Restaurent instance used as an example.
     */
    public Restaurent getRestaurent() {
        return restaurent;
    }

    //------------------------
    // support for date ranges
    //------------------------    
    private DateRangeUtil createdDateRange = new DateRangeUtil("createdDate");
    private DateRangeUtil modifiedByRange = new DateRangeUtil("modifiedBy");

    /**
     * The {@link DateRangeUtil} for the createdDate attribute.
     */
    public DateRangeUtil getCreatedDateRange() {
        return createdDateRange;
    }

    /**
     * The {@link DateRangeUtil} for the modifiedBy attribute.
     */
    public DateRangeUtil getModifiedByRange() {
        return modifiedByRange;
    }

    @Override
    protected List<DateRange> getDateRanges() {
        List<DateRange> result = new ArrayList<DateRange>();
        result.add(getCreatedDateRange());
        result.add(getModifiedByRange());
        return result;
    }

    private NullRestriction photoNullRestriction = new NullRestriction("photo");

    public NullRestriction getPhotoNullRestriction() {
        return photoNullRestriction;
    }

    @Override
    public List<NullRestriction> getNullRestrictions() {
        List<NullRestriction> result = new ArrayList<NullRestriction>();
        result.add(photoNullRestriction);
        return result;
    }
}