/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/test/java/domain/ModelTest.e.vm.java
 */
package com.mgt.mycity.domain;

import java.io.*;
import java.util.*;

import static org.junit.Assert.*;
import org.junit.Test;

import com.mgt.mycity.util.*;
import static javax.persistence.CascadeType.PERSIST;
import static org.hibernate.annotations.CacheConcurrencyStrategy.NONSTRICT_READ_WRITE;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQuery;
import javax.persistence.QueryHint;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;
import org.apache.log4j.Logger;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.Filter;
import org.hibernate.annotations.FilterDef;
import org.hibernate.annotations.ParamDef;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;
import com.mgt.mycity.domain.Role;
import com.mgt.mycity.validation.JpaUnique;

/**
 * Basic tests for User
 */
public class UserTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        User model = new User();
        assertFalse(model.isPrimaryKeySet());
    }

    @Test
    public void isPrimaryKeySetReturnsTrue() {
        User model = new User();
        model.setUserId(ValueGenerator.getUniqueNumeric(Integer.class, "2147483647"));
        assertNotNull(model.getUserId());
        assertTrue(model.isPrimaryKeySet());
    }

    // test columns methods

    //-------------------------------------------------------------
    // Pure Many to Many
    //-------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @Test
    public void manyToMany_addRole() {
        User many1 = new User();
        Role many2 = new Role();

        // add it
        many1.addRole(many2);

        // check it is propagated
        assertTrue(many1.containsRole(many2));
        // now let's remove it
        many1.removeRole(many2);

        // check it is propagated
        assertFalse(many1.containsRole(many2));
    }

    @Test
    public void toStringNotNull() {
        User model = new User();
        assertNotNull(model.toString());
    }

    @Test
    public void equalsUsingPk() {
        User model1 = new User();
        User model2 = new User();

        model1.setEmailaddress("dummy@dummy.com");
        model2.setEmailaddress("dummy@dummy.com");

        model1.setPassword("d");
        model2.setPassword("d");

        model1.setEnabled("d");
        model2.setEnabled("d");

        Integer userId = ValueGenerator.getUniqueNumeric(Integer.class, "2147483647");
        model1.setUserId(userId);
        model2.setUserId(userId);
        assertTrue(model1.isPrimaryKeySet());
        assertTrue(model2.isPrimaryKeySet());
        assertTrue(model1.hashCode() == model2.hashCode());
        assertTrue(model1.equals(model2));
        assertTrue(model2.equals(model1));
    }
}