/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.mgt.mycity.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.mgt.mycity.dao.support.GenericDao;
import com.mgt.mycity.service.support.GenericEntityServiceImpl;
import com.mgt.mycity.domain.Category;
import com.mgt.mycity.dao.CategoryDao;

/**
 *
 * Default implementation of the {@link CategoryService} interface
 * @see CategoryService
 */
@Service("categoryService")
public class CategoryServiceImpl extends GenericEntityServiceImpl<Category, Integer> implements CategoryService {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(CategoryServiceImpl.class);

    protected CategoryDao categoryDao;

    @Autowired
    public void setCategoryDao(CategoryDao categoryDao) {
        this.categoryDao = categoryDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Category, Integer> getDao() {
        return categoryDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Category getNew() {
        return new Category();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Category getNewWithDefaults() {
        Category result = getNew();
        result.initDefaultValues();
        return result;
    }

}