/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.mgt.mycity.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.mgt.mycity.dao.support.GenericDao;
import com.mgt.mycity.service.support.GenericEntityServiceImpl;
import com.mgt.mycity.domain.Photo;
import com.mgt.mycity.dao.PhotoDao;

/**
 *
 * Default implementation of the {@link PhotoService} interface
 * @see PhotoService
 */
@Service("photoService")
public class PhotoServiceImpl extends GenericEntityServiceImpl<Photo, Integer> implements PhotoService {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(PhotoServiceImpl.class);

    protected PhotoDao photoDao;

    @Autowired
    public void setPhotoDao(PhotoDao photoDao) {
        this.photoDao = photoDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Photo, Integer> getDao() {
        return photoDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Photo getNew() {
        return new Photo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Photo getNewWithDefaults() {
        Photo result = getNew();
        result.initDefaultValues();
        return result;
    }

}