/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.mgt.mycity.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.mgt.mycity.dao.support.GenericDao;
import com.mgt.mycity.service.support.GenericEntityServiceImpl;
import com.mgt.mycity.domain.Restaurent;
import com.mgt.mycity.dao.RestaurentDao;

/**
 *
 * Default implementation of the {@link RestaurentService} interface
 * @see RestaurentService
 */
@Service("restaurentService")
public class RestaurentServiceImpl extends GenericEntityServiceImpl<Restaurent, Integer> implements RestaurentService {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(RestaurentServiceImpl.class);

    protected RestaurentDao restaurentDao;

    @Autowired
    public void setRestaurentDao(RestaurentDao restaurentDao) {
        this.restaurentDao = restaurentDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Restaurent, Integer> getDao() {
        return restaurentDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Restaurent getNew() {
        return new Restaurent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Restaurent getNewWithDefaults() {
        Restaurent result = getNew();
        result.initDefaultValues();
        return result;
    }

}