/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.mgt.mycity.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.mgt.mycity.dao.support.GenericDao;
import com.mgt.mycity.service.support.GenericEntityServiceImpl;
import com.mgt.mycity.domain.Role;
import com.mgt.mycity.dao.RoleDao;

/**
 *
 * Default implementation of the {@link RoleService} interface
 * @see RoleService
 */
@Service("roleService")
public class RoleServiceImpl extends GenericEntityServiceImpl<Role, Integer> implements RoleService {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(RoleServiceImpl.class);

    protected RoleDao roleDao;

    @Autowired
    public void setRoleDao(RoleDao roleDao) {
        this.roleDao = roleDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<Role, Integer> getDao() {
        return roleDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Role getNew() {
        return new Role();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Role getNewWithDefaults() {
        Role result = getNew();
        result.initDefaultValues();
        return result;
    }

}