/*
 * (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to use Celerio within your company? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Template pack-backend:src/main/java/project/manager/ManagerImpl.e.vm.java
 */
package com.mgt.mycity.service;

import org.apache.log4j.Logger;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.mgt.mycity.dao.support.GenericDao;
import com.mgt.mycity.service.support.GenericEntityServiceImpl;
import com.mgt.mycity.domain.User;
import com.mgt.mycity.dao.UserDao;

/**
 *
 * Default implementation of the {@link UserService} interface
 * @see UserService
 */
@Service("userService")
public class UserServiceImpl extends GenericEntityServiceImpl<User, Integer> implements UserService {

    @SuppressWarnings("unused")
    private static final Logger log = Logger.getLogger(UserServiceImpl.class);

    protected UserDao userDao;

    @Autowired
    public void setUserDao(UserDao userDao) {
        this.userDao = userDao;
    }

    /**
     * Dao getter used by the {@link GenericEntityServiceImpl}.
     */
    @Override
    public GenericDao<User, Integer> getDao() {
        return userDao;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User getNew() {
        return new User();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public User getNewWithDefaults() {
        User result = getNew();
        result.initDefaultValues();
        return result;
    }

}