<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/domain/create.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="spring" uri="http://www.springframework.org/tags"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="restaurent" />: <fmt:message key="crud.functionalities.create" /></title>
</head>
<body>
	<a href="${pageContext.request.contextPath}/domain/restaurent/search" class="ajaxy button button-search"><fmt:message key="restaurent" /></a>
	<span class="ui-state-highlight button button-create"><fmt:message key="crud.functionalities.create" /></span>
	<form:form action="${pageContext.request.contextPath}/domain/restaurent/create" modelAttribute="restaurent" method="POST">
		<form:errors cssClass="error"/>
		<form:hidden path="restaurentId"/>
		<table class="create">
			<tbody>
				<tr>
					<th><fmt:message key="restaurent_code" /> <em>*</em></th>
					<td>
						<form:input path="code" cssClass="required {maxlength: 10}" maxlength="10" size="30"/>
						<form:errors path="code" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_name" /> <em>*</em></th>
					<td>
						<form:input path="name" cssClass="required {maxlength: 10}" maxlength="10" size="30"/>
						<form:errors path="name" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_desc" /></th>
					<td>
						<form:textarea path="desc" cssClass="{maxlength: 500}"/>
						<form:errors path="desc" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_photoId" /></th>
					<td>
						<input type="hidden" id="photoLink" name="photo" value="<spring:eval expression="restaurent.photoId" javaScriptEscape="true"/>" />
						<input type="text" id="photoLabel" value="<spring:eval expression="restaurent.photo" javaScriptEscape="true"/>" size="100">
						<script>
						$(function() {
							$("#photoLabel").autocomplete('destroy');
							$("#photoLabel").autocomplete({
								source: "${pageContext.request.contextPath}/domain/rest/photo/autocomplete",
								select: function(event, ui) {
									$("#photoLink").val(ui.item.id);
									$("#photoLabel").val(ui.item.label);
								}
							});
						});
						</script>
						<form:errors path="photo" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_isActive" /></th>
					<td>
						<form:input path="isActive" cssClass="{maxlength: 1}" maxlength="1" size="1"/>
						<form:errors path="isActive" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_createdDate" /> <em>*</em></th>
					<td>
						<form:input path="createdDate" cssClass="datepicker required" size="11"/>
						<form:errors path="createdDate" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_createdBy" /> <em>*</em></th>
					<td>
						<form:input path="createdBy" cssClass="required {maxlength: 26}" maxlength="26" size="30"/>
						<form:errors path="createdBy" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_modifiedBy" /></th>
					<td>
						<form:input path="modifiedBy" cssClass="datepicker" size="11"/>
						<form:errors path="modifiedBy" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_modifiedDate" /></th>
					<td>
						<form:input path="modifiedDate" cssClass="{maxlength: 26}" maxlength="26" size="30"/>
						<form:errors path="modifiedDate" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="category" /></th>
					<td>
						<form:select path="categories" multiple="true" items="${categories}" itemValue="primaryKey"/>
						<form:errors path="categories" cssClass="error"/>
					</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">
						<input type="submit" class="button button-save" value="<fmt:message key="crud.save.button" />"/>
					</td>
				</tr>
			</tfoot>
		</table>
	</form:form>
</body>
