<%--
 | (c) Copyright 2005-2012 JAXIO, www.jaxio.com
 | Source code generated by Celerio, a Jaxio product
 | Want to use Celerio within your company? email us at info@jaxio.com
 | Follow us on twitter: @springfuse
 | Template pack-mvc-3:src/main/webapp/WEB-INF/views/domain/search.e.vm.jsp
--%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"
%><%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"
%><%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"
%><%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"
%><head>
	<title><fmt:message key="restaurent" />: <fmt:message key="crud.functionalities.example" /></title>
</head>
<body>
	<span class="ui-state-highlight button button-search"><fmt:message key="restaurent" /></span> 
	<a href="${pageContext.request.contextPath}/domain/restaurent/create" class="button button-create"><fmt:message key="crud.functionalities.create" /></a> 
	<a href="${pageContext.request.contextPath}/domain/restaurent/showcase" class="button button-create"><fmt:message key="crud.functionalities.showcase" /></a>

	<form:form action="${pageContext.request.contextPath}/domain/restaurent/list" modelAttribute="restaurentSearchForm" class="search">
		<table class="show">
			<tbody>
				<tr>
					<th><fmt:message key="restaurent_code" /></th>
					<td>
						<form:input path="restaurent.code"/>
						<form:errors path="restaurent.code" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_name" /></th>
					<td>
						<form:input path="restaurent.name"/>
						<form:errors path="restaurent.name" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_desc" /></th>
					<td>
						<form:textarea path="restaurent.desc"/>
						<form:errors path="restaurent.desc" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_photoId" /></th>
					<td>
						<form:select id="photoRestriction" path="photoNullRestriction.restriction" cssClass="number">
							<form:options />
						</form:select>
						<script>
						$('#photoRestriction').change(function() {
							if ($('#photoRestriction option:selected').val() == 'SPECIFIED') { 
								$('#photoLink,#photoLabel').removeAttr('disabled');
								$('#photoLabel').focus();
							} else { 
								$('#photoLink,#photoLabel').attr('disabled', 'disabled'); 
							}
						});
						</script>
						<form:hidden id="photoLink" path="restaurent.photo" />
						<input type="text" id="photoLabel"  size="100">
						<script>
						$(function() {
							$('#photoLabel').autocomplete('destroy');
							$('#photoLabel').autocomplete({
								source: "${pageContext.request.contextPath}/domain/rest/photo/autocomplete",
								select: function(event, ui) {
									$('#photoLink').val(ui.item.id);
									$('#photoLabel').val(ui.item.label);
								}
							});
						});
						</script>
						<form:errors path="restaurent.photoId" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_isActive" /></th>
					<td>
						<form:input path="restaurent.isActive"/>
						<form:errors path="restaurent.isActive" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_createdDate" /></th>
					<td>
						<label for="createdDateRange.fromDate"><fmt:message key="search.date.from" /></label>
						<form:input path="createdDateRange.fromDate" cssClass="datepicker"/>
						<label for="createdDateRange.toDate"><fmt:message key="search.date.to" /></label>
						<form:input path="createdDateRange.toDate" cssClass="datepicker"/>
						<form:errors path="restaurent.createdDate" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_createdBy" /></th>
					<td>
						<form:input path="restaurent.createdBy"/>
						<form:errors path="restaurent.createdBy" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_modifiedBy" /></th>
					<td>
						<label for="modifiedByRange.fromDate"><fmt:message key="search.date.from" /></label>
						<form:input path="modifiedByRange.fromDate" cssClass="datepicker"/>
						<label for="modifiedByRange.toDate"><fmt:message key="search.date.to" /></label>
						<form:input path="modifiedByRange.toDate" cssClass="datepicker"/>
						<form:errors path="restaurent.modifiedBy" cssClass="error"/>
					</td>
				</tr>
				<tr>
					<th><fmt:message key="restaurent_modifiedDate" /></th>
					<td>
						<form:input path="restaurent.modifiedDate"/>
						<form:errors path="restaurent.modifiedDate" cssClass="error"/>
					</td>
				</tr>
			</tbody>
			<tfoot>
				<tr>
					<td colspan="2">
						<input type="submit" class="button button-search" value="<fmt:message key="crud.search.button" />"/>
					</td>
				</tr>
			</tfoot>
		</table>
	</form:form>
	<div id="result"/>
</body>
