package com.mgt.findmycity.domain;
// Generated Feb 10, 2012 3:23:57 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * Ingredients generated by hbm2java
 */
@Entity
@Table(name="ingredients"
    ,catalog="findmycity"
, uniqueConstraints = {  }
)

public class Ingredients  implements java.io.Serializable {


    // Fields    

     private int id;
     private String name;
     private String description;
     private Set<MenuItemIngredients> menuItemIngredientses = new HashSet<MenuItemIngredients>(0);


    // Constructors

    /** default constructor */
    public Ingredients() {
    }

	/** minimal constructor */
    public Ingredients(int id, String name, String description) {
        this.id = id;
        this.name = name;
        this.description = description;
    }
    
    /** full constructor */
    public Ingredients(int id, String name, String description, Set<MenuItemIngredients> menuItemIngredientses) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.menuItemIngredientses = menuItemIngredientses;
    }
    

   
    // Property accessors
    @Id
    @Column(name="ID", unique=true, nullable=false, insertable=true, updatable=true)

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    @Column(name="NAME", unique=false, nullable=false, insertable=true, updatable=true, length=45)

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="DESCRIPTION", unique=false, nullable=false, insertable=true, updatable=true)

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @OneToMany(cascade={CascadeType.ALL}, fetch=FetchType.LAZY, mappedBy="ingredients")

    public Set<MenuItemIngredients> getMenuItemIngredientses() {
        return this.menuItemIngredientses;
    }
    
    public void setMenuItemIngredientses(Set<MenuItemIngredients> menuItemIngredientses) {
        this.menuItemIngredientses = menuItemIngredientses;
    }
   








}
