package com.mgt.findmycity.domain;
// Generated Feb 17, 2012 3:11:56 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.Column;
import javax.persistence.Embeddable;


/**
 * RestaurentCategoryId generated by hbm2java
 */
@Embeddable

public class RestaurentCategoryId  implements java.io.Serializable {


    // Fields    

     private int restaurentId;
     private int categoryId;


    // Constructors

    /** default constructor */
    public RestaurentCategoryId() {
    }

    
    /** full constructor */
    public RestaurentCategoryId(int restaurentId, int categoryId) {
        this.restaurentId = restaurentId;
        this.categoryId = categoryId;
    }
    

   
    // Property accessors
    @Column(name="RESTAURENT_ID", unique=false, nullable=false, insertable=true, updatable=true)

    public int getRestaurentId() {
        return this.restaurentId;
    }
    
    public void setRestaurentId(int restaurentId) {
        this.restaurentId = restaurentId;
    }
    @Column(name="CATEGORY_ID", unique=false, nullable=false, insertable=true, updatable=true)

    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RestaurentCategoryId) ) return false;
		 RestaurentCategoryId castOther = ( RestaurentCategoryId ) other; 
         
		 return (this.getRestaurentId()==castOther.getRestaurentId())
 && (this.getCategoryId()==castOther.getCategoryId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRestaurentId();
         result = 37 * result + this.getCategoryId();
         return result;
   }   





}
