package com.mgt.findmycity.domain;
// Generated Feb 17, 2012 3:11:56 PM by Hibernate Tools 3.1.0.beta4

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name="user_role"
    ,catalog="findmycity"
)

public class UserRole  implements java.io.Serializable {


    // Fields    

     private UserRoleId id;
     private Role role;
     private User user;


    // Constructors

    /** default constructor */
    public UserRole() {
    }

    
    /** full constructor */
    public UserRole(UserRoleId id, Role role, User user) {
        this.id = id;
        this.role = role;
        this.user = user;
    }
    

   
    // Property accessors
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="userId", column=@Column(name="user_id", unique=false, nullable=false, insertable=true, updatable=true) ), 
        @AttributeOverride(name="roleId", column=@Column(name="role_id", unique=false, nullable=false, insertable=true, updatable=true) ) } )

    public UserRoleId getId() {
        return this.id;
    }
    
    public void setId(UserRoleId id) {
        this.id = id;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="role_id", unique=false, nullable=false, insertable=false, updatable=false)

    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    @ManyToOne(cascade={},
        fetch=FetchType.LAZY)
    
        @JoinColumn(name="user_id", unique=false, nullable=false, insertable=false, updatable=false)

    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
   








}
